#-------------------------------
# General Site Settings

title: Doobyeol
logo: 
author: Doobyeol Kim
description: Doobyeol Portfolio
email: doobyeol@gmail.com
phone: 010 5573 6409
address: Seoul, Korea
copyright: Copyright &copy; 2022 [Doobyeol](https://github.com/doobyeol) ALL RIGHTS RESERVED.

menu:
- {name: About, link: '/about'}
- {name: Blog, link: '/blog'}
- {name: Portfolio, link: '/portfolio'}
- {name: Contact, link: '/contact'}


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: Hi! my dream is to become a Full Stack developer.


social:
- {icon: "ti-github", link: "https://github.com/doobyeol"}
- {icon: "ti-vimeo", link: "https://velog.io/@doobyeol"}
- {icon: "ti-email", link: "mailto:doobyeol@gmail.com"}
- {icon: "ti-youtube", link: "https://www.youtube.com/channel/UCUsRgVZMqpKX9YBlEG1lZhg"}


#-------------------------------
# About (Section and Page)

# About Section
blurb:
  개발을 할 때 푹 빠져드는 재미와 못하는 것을 되게 하고자 하는 호기심. 그리고 해냈을 때의 성취감은 말로 표현할 수 없는 저의 원동력입니다. 성실함과 꾸준함, 끈기로 늘 성장하는 개발자가 되겠습니다.

blurb-btn-link: '/about'
blurb-btn-name: know more


# About Page

# Work Process Section
work-process:
  - title : "Research and Plan"
    icon : "assets/images/icons/plan.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    
  - title : "Design and Develop"
    icon : "assets/images/icons/design.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    
  - title : "Deliver"
    icon : "assets/images/icons/print.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."


# My Team Section
team:
  - title : "Jack Schenziwe"
    image : "assets/images/team/member-1.png"
    designation : "Project Manager"
    
  - title : "Julias Carlie"
    image : "assets/images/team/member-2.png"
    designation : "Web Developer"
    
  - title : "John Doe"
    image : "assets/images/team/member-3.png"
    designation : "Designer"


#-------------------------------
# Skills Section

skills-title: Skills
skills:
- {name: JavaScript, color: '#fdb157', value: '70%'}
- {name: Java, color: '#9473e6', value: '40%'}
- {name: SQL, color: '#bdecf6', value: '60%'}
- {name: HTML&CSS, color: '#ffbcaa', value: '90%'}


#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
- {name: Web & App Publisher, icon: 'icon-1.png', date: '2018.10 - 2020.02', organization: 'Soltworks'}
- {name: Web Publisher, icon: 'icon-2.png', date: '2020.03 - 2021.01', organization: 'Freelancer'}
- {name: Web Developer, icon: 'icon-3.png', date: '2021.07 - 재직중', organization: 'SPH'}


#-------------------------------
# Education Section

education-title: Education
education:
- {name: 디지털컨버전스 딥러닝 웹 개발자 양성과정, date: '2021', organization: '비트캠프'}
- {name: UI&UX디자인&퍼블리싱, date: '2018', organization: '그린컴퓨터아트학원'}
- {name: 미디어 디자인, date: '2018', organization: '용인대학교'}
- {name: 영상 디자인, date: '2014', organization: '서울디자인고등학교'}


#-------------------------------
# Services Section

services-title: Tech Stack
services:
- {
    name: BackEnd,
    icon: ti-server,
    description: 'Java, Node.js, Linux, MySQL, Oracle, PostgreSQL',
    active: # Add true to select section
  }
- {
    name: FrontEnd,
    icon: ti-layers,
    description: 'HTML5, CSS3, jQuery, JavaScript, Vue, Node.js',
    active: true # Add true to select section
  }
- {
    name: Etc,
    icon: ti-world,
    description: 'Git, Github',
    active: # Add true to select section
  }



#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-2.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-4.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-5.png"
    url: "#"


# Portfolio Page
portfolio-label:
- {
    title : "UI/UX Design",
    type : "design"
  }
- {
    title : "BRANDING",
    type : "branding"
  }
- {
    title : "ILLUSTRATION",
    type : "illustration"
  }

portfolio-items:
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
     - type: "design"
     - type: "illustration"
      
  - image : "assets/images/portfolio/item-2.png"
    url: "#"
    portfolio-type:
      - type: "branding"
      
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "illustration"
      
  - image : "assets/images/portfolio/item-6.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "branding"
      
  - image : "assets/images/portfolio/item-8.png"
    url: "#"
    portfolio-type:
      - type: "illustration"
      
  - image : "assets/images/portfolio/item-5.png"
    url: "#"
    portfolio-type:
      - type: "design"
      
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "branding"
      
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"
      - type: "branding"
      
  - image : "assets/images/portfolio/item-7.png"
    url: "#"
    portfolio-type:
      - type: "illustration"


#-------------------------------
# Testimonials Section

testimonial-items:
  - name: "Jesica Gomez"
    image: "assets/images/testimonial/client-1.png"
    designation : "CEO, Funder"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
    
  - name: "Jesica Gomez"
    image: "assets/images/testimonial/client-1.png"
    designation: "CEO, Funder"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
    
  - name: "Jesica Gomez"
    image: "assets/images/testimonial/client-1.png"
    designation: "CEO, Funder"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."


#-------------------------------
# Client Slider Section

client-slider-items:
  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: steve.fruits@email.com
